// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ6mIOUbOyBFkTTQkQaftLmWo3VMG6VqU',
    appId: '1:911480728638:web:33b7adc824197300e0756f',
    messagingSenderId: '911480728638',
    projectId: 'siatrab-53f04',
    authDomain: 'siatrab-53f04.firebaseapp.com',
    storageBucket: 'siatrab-53f04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wJ2DEZFq9dUcj_2iSaXG6PQvScw2S2U',
    appId: '1:911480728638:android:fd0c292539fe5e8de0756f',
    messagingSenderId: '911480728638',
    projectId: 'siatrab-53f04',
    storageBucket: 'siatrab-53f04.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ6mIOUbOyBFkTTQkQaftLmWo3VMG6VqU',
    appId: '1:911480728638:web:c259fba47b7ada98e0756f',
    messagingSenderId: '911480728638',
    projectId: 'siatrab-53f04',
    authDomain: 'siatrab-53f04.firebaseapp.com',
    storageBucket: 'siatrab-53f04.firebasestorage.app',
  );
}
